version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOWKIDAR_USEPOLLING=true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    stdin_open: true
    environment:
      - CHOWKIDAR_USEPOLLING=true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm','run','build']